fieldLayouts:
  a5a5cbac-bbcf-4ce4-8824-ac92ee387d7c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0edf4f32-bf69-4ef2-aa9a-a57b5bad42a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c5542d7d-f0e2-4f91-996e-f7480b4c4472 # Full Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a682e3c6-fcfe-436d-b88e-58d5cff51af3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f7ae64d3-2ec5-4d96-96d0-877f7a9c8c87 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f76d336-c1be-4812-9d28-5810f17cbfee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 38e8d8ca-544b-4333-a940-d38cada2e2b6
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: d8b4fdc3-e87f-4bd9-bb3c-1e0d19ab54d1 # Image Slides
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
