fieldLayouts:
  760dba6a-b54d-44ba-991c-bac2d73b4f49:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5345bbf3-752c-4113-892d-6f3955220f68
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 251f925a-95d1-42e0-b967-a360c80d963e # Components
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3cb2452-0715-4b06-88e9-70d0d6c14e69
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5da74c11-8df6-47d9-8135-b3cf5851124e
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: be11218f-d920-4770-854e-c1366c1566a6 # General Pages
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
